COREVNNET/Areas/Root/Models/DataModels/Administrator.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace COREVNNET.Areas.Root.Models.DataModels
{
    [Table("Administrator")]
    public class Administrator
    {
        [Display(Name ="Mã Administrator")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }

        [Required(ErrorMessage ="Phải nhập username")]
        [Display(Name ="Username của admin")]
        [StringLength(77,ErrorMessage ="Username phải từ 3 đến 77 ký tự"),MinLength(3)]
        [Column(TypeName ="varchar")]
        public string Username { get; set; }

        [Required(ErrorMessage ="Phải nhập họ tên admin")]
        [Display(Name ="Họ và tên Admin")]
        [Column(TypeName ="nvarchar")]
        [StringLength(27,ErrorMessage ="Họ và tên phải từ 7 đến 32 ký tự"),MinLength(7)]
        public string FullName { get; set; }

        [Required(ErrorMessage ="Xin nhập Password")]
        [Display(Name ="Mật khẩu")]
        [Column(TypeName ="varchar")]
        [StringLength(256,ErrorMessage ="Mật khẩu phải lớn hơn 3 ký tự"),MinLength(3)]
        public string PassWord { get; set; }

        [Required(ErrorMessage ="Nhập email")]
        [EmailAddress(ErrorMessage ="Email không đúng định dạng")]
        [Column(TypeName ="varchar")]
        [MaxLength(256)]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Display(Name ="Ảnh đại diện")]
        [Column(TypeName ="varchar")]
        [MaxLength(256)]
        public string Avatar { get; set; }

        [Display(Name = "Là Admin(1 là admin)")]
        public byte? IsAdmin { get; set; }

        [Display(Name ="Trang thái kích hoạt")]
        public byte? Allowed { get; set; }
    }
}

COREVNNET/Areas/Root/Controllers/AdministratorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using COREVNNET.Areas.Root.Models.BusinessModels;
using COREVNNET.Areas.Root.Models.DataModels;

namespace COREVNNET.Areas.Root.Controllers
{
    [AttributeForAction]
    public class AdministratorsController : Controller
    {
        private CorevnNetContext db = new CorevnNetContext();

        // GET: Root/Administrators
        public ActionResult Index()
        {
            return View(db.Administrator.ToList());
        }

        // GET: Root/Administrators/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administrator administrator = db.Administrator.Find(id);
            if (administrator == null)
            {
                return HttpNotFound();
            }
            return View(administrator);
        }

        // GET: Root/Administrators/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Root/Administrators/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,Username,FullName,PassWord,Email,Avatar,IsAdmin,Allowed")] Administrator administrator)
        {
            administrator.PassWord = Common.EncryptMD5(administrator.Username + administrator.PassWord);
            if (ModelState.IsValid)
            {
                db.Administrator.Add(administrator);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(administrator);
        }

        // GET: Root/Administrators/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administrator administrator = db.Administrator.Find(id);
            if (administrator == null)
            {
                return HttpNotFound();
            }
            return View(administrator);
        }

        // POST: Root/Administrators/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Username,FullName,PassWord,Email,Avatar,IsAdmin,Allowed")] Administrator administrator)
        {
            if (ModelState.IsValid)
            {
                administrator.PassWord = Common.EncryptMD5(administrator.Username + administrator.PassWord);
                db.Entry(administrator).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(administrator);
        }

        // GET: Root/Administrators/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administrator administrator = db.Administrator.Find(id);
            if (administrator == null)
            {
                return HttpNotFound();
            }
            return View(administrator);
        }

        // POST: Root/Administrators/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Administrator administrator = db.Administrator.Find(id);
            db.Administrator.Remove(administrator);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

COREVNNET/Areas/Root/Controllers/GrantController.cs
using COREVNNET.Areas.Root.Models.BusinessModels;
using COREVNNET.Areas.Root.Models.DataModels;
using COREVNNET.Areas.Root.Models.Query;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace COREVNNET.Areas.Root.Controllers
{
    [AttributeForAction]
    public class GrantController : Controller
    {

        private CorevnNetContext db = new CorevnNetContext();
        // GET: Admin/Grant
        public ActionResult Index(int id)
        {
            //lấy tất cả các nghiệp vụ (controller) trong csdl
            var listcontrol = db.Business.AsEnumerable();
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var item in listcontrol)
            {
                items.Add(new SelectListItem() { Text = item.BusinessName, Value = item.BusinessId });
            }
            ViewBag.items = items;
            // lấy danh sách các quyền đã được cấp
            var list = db.GrantPermission.Join(db.Permission, g => g.PermissionId, p => p.PermissionId,
                (g, p) => new { Permission = p, GrantPermission = g }).
                Where(x => x.GrantPermission.UserId == id).AsEnumerable();
            List<SelectListItem> listGranted = new List<SelectListItem>();
            foreach (var item in list)
            {
                listGranted.Add(new SelectListItem() { Value = item.Permission.PermissionId.ToString(), Text = item.Permission.Description });
            }
            ViewBag.listGranted = listGranted;
            //lưu id của người dùng đang được câp ra session
            Session["usergrant"] = id;
            //lấy người dùng
            var usergrant = db.Administrator.Find(id);
            //lưu tên ra biến
            ViewBag.usergrant = usergrant.Username + "(" + usergrant.FullName + ")";
            ViewBag.usergrantimg = usergrant.Avatar;
            return View();
        }
        public JsonResult getPermissions(string id, int usertemp)
        {
            var listgranted = db.GrantPermission.Join(db.Permission, g => g.PermissionId, p => p.PermissionId
            , (g, p) => new PermissionAciton
            {
                PermissionId = p.PermissionId,
                PermissionName = p.PermissionName,
                Description = p.Description,
                IsGranted = true
            }
            ).ToList();

            // lấy tất cả các quyền của business hiện tại
            var listpermission = db.Permission.Where(x => x.BusinessId == id).Select(x => new PermissionAciton
            {
                PermissionId = x.PermissionId,
                PermissionName = x.PermissionName,
                Description = x.Description,
                IsGranted = false
            });
            //lay id cua permission da duoc gan o tren cho nguoi dung
            var listpermissionId = listgranted.Select(x => x.PermissionId);

            foreach (var item in listpermission)
            {
                if (!listpermissionId.Contains(item.PermissionId))
                {
                    listgranted.Add(item);
                }
            }
            return Json(listgranted.OrderBy(x => x.Description), JsonRequestBehavior.AllowGet);
        }
        public string updatePermission(int id, int usertemp)
        {
            string msg = "";
            var grant = db.GrantPermission.Find(id, usertemp);
            if (grant == null)
            {
                GrantPermission g = new GrantPermission() { PermissionId = id, UserId = usertemp, Description = "" };
                db.GrantPermission.Add(g);
                msg = "<div class ='alert alert-success'>Quyền cấp thành công</div>";
            }
            else
            {
                db.GrantPermission.Remove(grant);
                msg = "<div class = 'alert alert-danger'>Hủy quyền thành công</div>";
            }
            db.SaveChanges();
            return msg;
        }

    }

}

COREVNNET/Areas/Root/Views/Administrators/Create.cshtml
@model COREVNNET.Areas.Root.Models.DataModels.Administrator

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Administrator</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger", type = "password" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsAdmin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Allowed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Allowed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Allowed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

COREVNNET/Areas/Root/Views/Administrators/Delete.cshtml
@model COREVNNET.Areas.Root.Models.DataModels.Administrator

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Administrator</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassWord)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassWord)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allowed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allowed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

COREVNNET/Areas/Root/Views/Administrators/Details.cshtml
@model COREVNNET.Areas.Root.Models.DataModels.Administrator

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Administrator</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassWord)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassWord)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allowed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allowed)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

COREVNNET/Areas/Root/Views/Administrators/Edit.cshtml
@model COREVNNET.Areas.Root.Models.DataModels.Administrator

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Administrator</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsAdmin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Allowed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Allowed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Allowed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

COREVNNET/Areas/Root/Views/Administrators/Index.cshtml
@model IEnumerable<COREVNNET.Areas.Root.Models.DataModels.Administrator>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PassWord)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Avatar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Allowed)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PassWord)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Avatar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAdmin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Allowed)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
            @Html.ActionLink("Cấp quyền", "Index","Grant", new { id=item.UserId},null)
        </td>
    </tr>
}

</table>