COREVNNET/Areas/Root/Controllers/BusinessesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using COREVNNET.Areas.Root.Models.BusinessModels;
using COREVNNET.Areas.Root.Models.DataModels;

namespace COREVNNET.Areas.Root.Controllers
{
    [AttributeForAction]
    public class BusinessesController : Controller
    {
        private CorevnNetContext db = new CorevnNetContext();

        //cập nhật controller
        public ActionResult Update()
        {
            Reflection rc = new Reflection();
            List<Type> listControllerType = rc.GetControllers("COREVNNET.Areas.Root.Controllers");
            List<string> listControllerOld = db.Business.Select(c => c.BusinessId).ToList();
            List<string> listPermissionOld = db.Permission.Select(p => p.PermissionName).ToList();
            foreach (var c in listControllerType)
            {
                if (!listControllerOld.Contains(c.Name))
                {
                    Business b = new Business()
                    {
                        BusinessId = c.Name,
                        BusinessName = "Chưa có mô tả"
                    };
                    db.Business.Add(b);
                }
                List<string> listPermission = rc.GetAction(c);
                foreach (var p in listPermission)
                {
                    if (!listPermissionOld.Contains(c.Name + "-" + p))
                    {
                        Permission permission = new Permission()
                        {
                            PermissionName = c.Name + "-" + p,
                            Description = "Chưa có mô tả",
                            BusinessId = c.Name
                        };
                        db.Permission.Add(permission);
                    }
                }
            }
            db.SaveChanges();
            TempData["err"] = "<div class='alert alert-info' role='alert'><span class='glyphicon glyphicon-exclamation-sign' aria-hidden='true'></span><span class='sr-only'></span> Cập nhật thành công</div>";
            return RedirectToAction("Index");
        }
        // GET: Root/Businesses
        public ActionResult Index()
        {
            return View(db.Business.ToList());
        }

        // GET: Root/Businesses/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.Business.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            return View(business);
        }

        // GET: Root/Businesses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Root/Businesses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BusinessId,BusinessName")] Business business)
        {
            if (ModelState.IsValid)
            {
                db.Business.Add(business);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(business);
        }

        // GET: Root/Businesses/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.Business.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            return View(business);
        }

        // POST: Root/Businesses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BusinessId,BusinessName")] Business business)
        {
            if (ModelState.IsValid)
            {
                db.Entry(business).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(business);
        }

        // GET: Root/Businesses/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.Business.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            return View(business);
        }

        // POST: Root/Businesses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Business business = db.Business.Find(id);
            db.Business.Remove(business);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

COREVNNET/Areas/Root/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using COREVNNET.Areas.Root.Models.BusinessModels;
using COREVNNET.Areas.Root.Models.DataModels;

namespace COREVNNET.Areas.Root.Controllers
{
    [AttributeForAction]
    public class PermissionsController : Controller
    {
        private CorevnNetContext db = new CorevnNetContext();

        // GET: Root/Permissions
        public ActionResult Index(string id)
        {
            var permission = db.Permission.Where(x => x.BusinessId == id);
            return View(permission.ToList());
        }

        // GET: Root/Permissions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permission.Find(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        // GET: Root/Permissions/Create
        public ActionResult Create()
        {
            ViewBag.BusinessId = new SelectList(db.Business, "BusinessId", "BusinessName");
            return View();
        }

        // POST: Root/Permissions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PermissionId,PermissionName,Description,BusinessId")] Permission permission)
        {
            if (ModelState.IsValid)
            {
                db.Permission.Add(permission);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BusinessId = new SelectList(db.Business, "BusinessId", "BusinessName", permission.BusinessId);
            return View(permission);
        }

        // GET: Root/Permissions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permission.Find(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            ViewBag.BusinessId = new SelectList(db.Business, "BusinessId", "BusinessName", permission.BusinessId);
            return View(permission);
        }

        // POST: Root/Permissions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PermissionId,PermissionName,Description,BusinessId")] Permission permission)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permission).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BusinessId = new SelectList(db.Business, "BusinessId", "BusinessName", permission.BusinessId);
            return View(permission);
        }

        // GET: Root/Permissions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permission.Find(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        // POST: Root/Permissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Permission permission = db.Permission.Find(id);
            db.Permission.Remove(permission);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

COREVNNET/Areas/Root/Views/Businesses/Create.cshtml
@model COREVNNET.Areas.Root.Models.DataModels.Business

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Business</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BusinessId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusinessId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BusinessName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusinessName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

COREVNNET/Areas/Root/Views/Businesses/Delete.cshtml
@model COREVNNET.Areas.Root.Models.DataModels.Business

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Business</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BusinessName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

COREVNNET/Areas/Root/Views/Businesses/Details.cshtml
@model COREVNNET.Areas.Root.Models.DataModels.Business

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Business</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BusinessName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BusinessId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

COREVNNET/Areas/Root/Views/Businesses/Edit.cshtml
@model COREVNNET.Areas.Root.Models.DataModels.Business

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Business</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BusinessId)

        <div class="form-group">
            @Html.LabelFor(model => model.BusinessName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusinessName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

COREVNNET/Areas/Root/Views/Businesses/Index.cshtml
@model IEnumerable<COREVNNET.Areas.Root.Models.DataModels.Business>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Cập Nhật", "Update")
</p>
<p >@Html.Raw(TempData["err"])</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BusinessId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BusinessId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BusinessName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.BusinessId }) |
            @Html.ActionLink("Details", "Details", new { id = item.BusinessId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.BusinessId })|
            @Html.ActionLink("Danh sách các action", "Index", "Permissions", new { id= item.BusinessId},null)

        </td>
    </tr>
}

</table>